# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/v2g-demo/v2g-demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/v2g-demo/v2g-demo/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/v2g-demo/v2g-demo/build/CMakeFiles /home/runner/work/v2g-demo/v2g-demo/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/v2g-demo/v2g-demo/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mdflib

# Build rule for target.
mdflib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdflib
.PHONY : mdflib

# fast build rule for target.
mdflib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/build
.PHONY : mdflib/fast

ImportMdf4.o: ImportMdf4.cpp.o
.PHONY : ImportMdf4.o

# target to build an object file
ImportMdf4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/ImportMdf4.cpp.o
.PHONY : ImportMdf4.cpp.o

ImportMdf4.i: ImportMdf4.cpp.i
.PHONY : ImportMdf4.i

# target to preprocess a source file
ImportMdf4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/ImportMdf4.cpp.i
.PHONY : ImportMdf4.cpp.i

ImportMdf4.s: ImportMdf4.cpp.s
.PHONY : ImportMdf4.s

# target to generate assembly for a file
ImportMdf4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/ImportMdf4.cpp.s
.PHONY : ImportMdf4.cpp.s

export.o: export.cpp.o
.PHONY : export.o

# target to build an object file
export.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/export.cpp.o
.PHONY : export.cpp.o

export.i: export.cpp.i
.PHONY : export.i

# target to preprocess a source file
export.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/export.cpp.i
.PHONY : export.cpp.i

export.s: export.cpp.s
.PHONY : export.s

# target to generate assembly for a file
export.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/export.cpp.s
.PHONY : export.cpp.s

md5.o: md5.cpp.o
.PHONY : md5.o

# target to build an object file
md5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/md5.cpp.o
.PHONY : md5.cpp.o

md5.i: md5.cpp.i
.PHONY : md5.i

# target to preprocess a source file
md5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/md5.cpp.i
.PHONY : md5.cpp.i

md5.s: md5.cpp.s
.PHONY : md5.s

# target to generate assembly for a file
md5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/md5.cpp.s
.PHONY : md5.cpp.s

mdFile.o: mdFile.cpp.o
.PHONY : mdFile.o

# target to build an object file
mdFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/mdFile.cpp.o
.PHONY : mdFile.cpp.o

mdFile.i: mdFile.cpp.i
.PHONY : mdFile.i

# target to preprocess a source file
mdFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/mdFile.cpp.i
.PHONY : mdFile.cpp.i

mdFile.s: mdFile.cpp.s
.PHONY : mdFile.s

# target to generate assembly for a file
mdFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/mdFile.cpp.s
.PHONY : mdFile.cpp.s

mdf4.o: mdf4.cpp.o
.PHONY : mdf4.o

# target to build an object file
mdf4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/mdf4.cpp.o
.PHONY : mdf4.cpp.o

mdf4.i: mdf4.cpp.i
.PHONY : mdf4.i

# target to preprocess a source file
mdf4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/mdf4.cpp.i
.PHONY : mdf4.cpp.i

mdf4.s: mdf4.cpp.s
.PHONY : mdf4.s

# target to generate assembly for a file
mdf4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/mdf4.cpp.s
.PHONY : mdf4.cpp.s

stdafx.o: stdafx.cpp.o
.PHONY : stdafx.o

# target to build an object file
stdafx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/stdafx.cpp.o
.PHONY : stdafx.cpp.o

stdafx.i: stdafx.cpp.i
.PHONY : stdafx.i

# target to preprocess a source file
stdafx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/stdafx.cpp.i
.PHONY : stdafx.cpp.i

stdafx.s: stdafx.cpp.s
.PHONY : stdafx.s

# target to generate assembly for a file
stdafx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdflib.dir/build.make CMakeFiles/mdflib.dir/stdafx.cpp.s
.PHONY : stdafx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mdflib"
	@echo "... ImportMdf4.o"
	@echo "... ImportMdf4.i"
	@echo "... ImportMdf4.s"
	@echo "... export.o"
	@echo "... export.i"
	@echo "... export.s"
	@echo "... md5.o"
	@echo "... md5.i"
	@echo "... md5.s"
	@echo "... mdFile.o"
	@echo "... mdFile.i"
	@echo "... mdFile.s"
	@echo "... mdf4.o"
	@echo "... mdf4.i"
	@echo "... mdf4.s"
	@echo "... stdafx.o"
	@echo "... stdafx.i"
	@echo "... stdafx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

